import type { User, CarSetup } from "./types"

export const mockUsers: User[] = [
  { id: "1", name: "Alex Johnson", email: "alex@racing.com", role: "superuser" },
  { id: "2", name: "Sarah Chen", email: "sarah@racing.com", role: "admin" },
  { id: "3", name: "Mike Torres", email: "mike@racing.com", role: "user" },
  { id: "4", name: "Emma Davis", email: "emma@racing.com", role: "user" },
]

export const cars = [
  "Ferrari 488 GT3",
  "Porsche 911 GT3 R",
  "McLaren 720S GT3",
  "Audi R8 LMS GT3",
  "BMW M4 GT3",
  "Mercedes-AMG GT3",
]

export const tracks = [
  "Monza",
  "Spa-Francorchamps",
  "Nürburgring",
  "Silverstone",
  "Brands Hatch",
  "Imola",
  "Barcelona",
  "Paul Ricard",
]

export const seasons = ["2024 Season 1", "2024 Season 2", "2024 Season 3", "2025 Season 1"]

export const mockSetups: CarSetup[] = [
  {
    id: "1",
    name: "Monza Qualifying Setup",
    car: "Ferrari 488 GT3",
    track: "Monza",
    season: "2024 Season 3",
    week: 12,
    status: "approved",
    uploadedBy: "1",
    uploadedByName: "Alex Johnson",
    lastUpdated: new Date("2024-03-15"),
    notes: "Low downforce setup optimized for qualifying. Focus on top speed.",
    fileUrl: "/setups/monza-quali.sto",
    versions: [
      {
        id: "v1",
        version: 1,
        uploadedBy: "1",
        uploadedByName: "Alex Johnson",
        uploadedAt: new Date("2024-03-15"),
        changes: "Initial setup",
        status: "approved",
      },
    ],
  },
  {
    id: "2",
    name: "Spa Race Setup",
    car: "Porsche 911 GT3 R",
    track: "Spa-Francorchamps",
    season: "2024 Season 3",
    week: 11,
    status: "approved",
    uploadedBy: "2",
    uploadedByName: "Sarah Chen",
    lastUpdated: new Date("2024-03-14"),
    notes: "Balanced setup for race conditions. Good tire wear.",
    fileUrl: "/setups/spa-race.sto",
  },
  {
    id: "3",
    name: "Silverstone Wet Setup",
    car: "McLaren 720S GT3",
    track: "Silverstone",
    season: "2024 Season 3",
    week: 10,
    status: "pending",
    uploadedBy: "3",
    uploadedByName: "Mike Torres",
    lastUpdated: new Date("2024-03-13"),
    notes: "Setup for wet conditions. Needs testing.",
    fileUrl: "/setups/silverstone-wet.sto",
  },
  {
    id: "4",
    name: "Nürburgring Sprint",
    car: "Audi R8 LMS GT3",
    track: "Nürburgring",
    season: "2024 Season 3",
    week: 9,
    status: "approved",
    uploadedBy: "1",
    uploadedByName: "Alex Johnson",
    lastUpdated: new Date("2024-03-12"),
    notes: "Aggressive setup for sprint races.",
  },
  {
    id: "5",
    name: "Brands Hatch Test",
    car: "BMW M4 GT3",
    track: "Brands Hatch",
    season: "2025 Season 1",
    week: 1,
    status: "pending",
    uploadedBy: "4",
    uploadedByName: "Emma Davis",
    lastUpdated: new Date("2024-03-11"),
    notes: "Initial test setup for new season.",
  },
  {
    id: "6",
    name: "Imola Endurance",
    car: "Mercedes-AMG GT3",
    track: "Imola",
    season: "2024 Season 3",
    week: 8,
    status: "rejected",
    uploadedBy: "3",
    uploadedByName: "Mike Torres",
    lastUpdated: new Date("2024-03-10"),
    notes: "Setup for endurance racing. Too unstable in high-speed corners.",
  },
]
